### ISSUE TITLE
db_session needed?

### ISSUE THREAD

**Issue by cancan101** [jeancochrane/pytest-flask-sqlalchemy#4]
A usage question / request for clarification in the docs, but does the test need to use the `db_session` fixture, or is there a way to shim all usages of the session throughout the code? That way I can make sure to rollback the transaction anywhere there is an exception.

**Comment by jeancochrane** [comment]
Good question! Whenever the `db_session` fixture is listed as a dependency in a test's function arguments, it should automatically replace the connectables that are listed in your [configuration options](https://github.com/jeancochrane/pytest-flask-sqlalchemy#test-configuration) (either under `mocked-sessions`, `mocked-engines`, or `mocked-sessionmakers`). You don't have to actually call any methods of the `db_session` fixture to do this, since all of the shimming takes place in the fixture's [setup code](https://github.com/jeancochrane/pytest-flask-sqlalchemy/blob/master/pytest_flask_sqlalchemy/fixtures.py#L159-L162):

```python
# Whenever the code tries to access a Flask session, use the Session object
# instead
for mocked_session in pytestconfig._mocked_sessions:
    mocker.patch(mocked_session, new=session)
```

This is true for `db_engine` as well. Does that help address your question?

**Comment by cancan101** [comment]
Would the recommendation then to be use an auto use fixture of some sort?

**Comment by jeancochrane** [comment]
That's one way to do it! Although then all of your tests will load the fixtures, whether or not they touch the database -- since the transactional fixtures are function-scoped and require DB interaction, that might mean an unnecessary performance hit to your tests. So far I've always preferred listing the `db_session` dependency explicitly, although it can definitely feel overly verbose.

There had been some talk about introducing a simple mark like `@pytest.mark.transactional` that would load the shims in a test without explicitly requiring `db_session`. (In a [test implementation](https://github.com/jeancochrane/pytest-flask-sqlalchemy/commit/188a66fefa987660100583240c5923abb3204e94) I did a few months back, this basically meant that `db_session` would be automatically required as a dependency but not loaded into the body of the test -- so functionally identical to listing it in the parameters.) We decided against it because it seemed to not add value and was just another thing to document. For your use-case, would that be a more appealing solution than using either `usefixtures`/`autouse` or requiring it explicitly?

**Comment by cancan101** [comment]
I agree that the `autouse` seems less than ideal and I had some trouble actually getting it to work. What I am trying to address is the unfortunate nature that if any any test that I have that causes an issue with the transaction, all subsequent db related tests fail in unhelpful ways. Having to add `db_session` to all those tests is a PIA.

As far as explicit `db_session` vs decorator, the decorator might be better as it leads to to cleaner method signatures.

**Comment by jeancochrane** [comment]
Ah, I see what you're saying. I remember running into similar issues with shared connections that would continually error out when a `ProgrammingError` got raised in a transactional test, but the details are a little vague to me right now. If at all possible, I feel like the plugin should perform that error handling for you -- you shouldn't have to worry about adding transactional fixtures to tests that don't need them just to avoid annoying errors.

Do you have a traceback and/or a concrete test where you see this kind of behavior? No worries if not, it'll just help me investigate when I get a free minute to look into it.

**Comment by cancan101** [comment]
I figured out the issue I was having with `autouse` and now it works. I was trying to call the following in a teardown:
```python
    for table in reversed(db.metadata.sorted_tables):
        session.execute(table.delete())

    session.commit()
```
e.g. I had:
```python
@pytest.yield_fixture(autouse=True)
def populate_db(db_session):
    yield
    mock_data.clear() # code above
```
Given that I am rolling back, that clear isn't needed any more.

**Comment by jeancochrane** [comment]
Nice! So it sounds like the root issue was trying to run cleanup code using a closed connection after the rollback had already taken place.

**Comment by cancan101** [comment]
Yep so problem solved but I would suggest leaving this ticket open as TODO to add some notes to the docs about needing to use `db_session` either explicitly or with `autouse`.

**Comment by mbalaa-spring** [comment]
It appears that if you don't use `db_session` you run the risk of not having isolation across tests I decided to go the `autouse`;  would be nice if we could gaurd against db access without explicit declaration of `db_session`

**Comment by jeancochrane** [comment]
Thanks for the feedback @mbalaa-spring! Just added two new sections to the docs in https://github.com/jeancochrane/pytest-flask-sqlalchemy/commit/7e1e9e496f04cda635a8166abfc58fd821de2661, one to help clarify that a transactional fixture (like `db_session`) is required in order to enable transactions in a test, and one to suggest a solution for automatically enabling the fixture for all tests. For now I'm not planning on adding a feature to automatically enable transactions for all tests, mostly because the `autouse` workaround documented in https://github.com/jeancochrane/pytest-flask-sqlalchemy/commit/7e1e9e496f04cda635a8166abfc58fd821de2661 feels just as straightforward as any additional feature I could build on top of it. But if you have suggestions for a simple way to incorporate it into the plugin I'd be happy to review a PR.
